### ISSUE TITLE
Console tab-completion support

### ISSUE THREAD

**Issue by JorelAli** [JorelAli/CommandAPI#192]
**Please describe your suggestion**
tab-completion support for Brigadier commands is now a feature which has been merged to PaperSpigot (See [here](https://github.com/PaperMC/Paper/pull/5437) for all the details). The CommandAPI should support this, especially for cases where we assume a player is present when in fact the command can be executed by a console.

**Please supply examples of the desired inputs and outputs**
_Example:_
Input: `/teleport <targets> <location>`
Output: Tab completion should work, but instead goes potate because the CommandAPI tries to perform `getCLW(cmdCtx).getWorld().getWorld()`

Error log courtesy of @jpenilla
```
[17:11:26 INFO]: [org.jline] Error while finding completion candidates
--
  | java.lang.NullPointerException: null
  | at dev.jorel.commandapi.nms.NMS_1_16_R3.getLocation(NMS_1_16_R3.java:631) ~[?:?]
  | at dev.jorel.commandapi.CommandAPIHandler.parseArgument(CommandAPIHandler.java:295) ~[?:?]
  | at dev.jorel.commandapi.CommandAPIHandler.lambda$toSuggestions$17(CommandAPIHandler.java:744) ~[?:?]
  | at com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:71) ~[paper.jar:git-Paper-"10e7a2b92"]
  | at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:596) ~[paper.jar:git-Paper-"10e7a2b92"]
  | at io.papermc.paper.console.BrigadierCommandCompleter.complete(BrigadierCommandCompleter.java:40) ~[paper.jar:git-Paper-"10e7a2b92"]
  | at org.bukkit.craftbukkit.v1_16_R3.command.ConsoleCommandCompleter.addCompletions(ConsoleCommandCompleter.java:119) ~[paper.jar:git-Paper-"10e7a2b92"]
  | at org.bukkit.craftbukkit.v1_16_R3.command.ConsoleCommandCompleter.complete(ConsoleCommandCompleter.java:97) ~[paper.jar:git-Paper-"10e7a2b92"]
  | at org.jline.reader.impl.LineReaderImpl.doComplete(LineReaderImpl.java:4147) ~[paper.jar:git-Paper-"10e7a2b92"]
  | at org.jline.reader.impl.LineReaderImpl.expandOrComplete(LineReaderImpl.java:4060) ~[paper.jar:git-Paper-"10e7a2b92"]
  | at org.jline.reader.impl.LineReaderImpl$1.apply(LineReaderImpl.java:3630) ~[paper.jar:git-Paper-"10e7a2b92"]
  | at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:603) ~[paper.jar:git-Paper-"10e7a2b92"]
  | at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:418) ~[paper.jar:git-Paper-"10e7a2b92"]
  | at net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:158) ~[paper.jar:git-Paper-"10e7a2b92"]
  | at net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:141) ~[paper.jar:git-Paper-"10e7a2b92"]
  | at net.minecraft.server.v1_16_R3.DedicatedServer$1.run(DedicatedServer.java:106) ~[paper.jar:git-Paper-"10e7a2b92"]
  | > testzones 0 0 0


```

**Comment by JorelAli** [comment]
Implemented in 20386498dcc06609e1930d525f74e9faab099ff7 for 6.0.0.
