### ISSUE TITLE
Java IllegalAccessError

### ISSUE THREAD

**Issue by joeyPark8** [JorelAli/CommandAPI#202]
**CommandAPI version**
5.11

**Minecraft version**
1.16.5

**Describe the bug**
IllegalAccessError happened

**My code**
This code reproduces the behavior:
```java
CommandAPI.onLoad(true);
        List<Argument> arguments = new ArrayList<>();

        arguments.add(new GreedyStringArgument("text"));

        new CommandAPICommand("boo")
                .withArguments(arguments)
                .withAliases("b")
                .withPermission(CommandPermission.OP)
                .executesPlayer((player, args) -> {
                    player.sendMessage(ChatColor.BOLD + "SUCCESS " + args[0]);
                    System.out.println("SUCCESS " + args[0]);
                });
```

**Expected behavior**
How could I fix it?

**Additional context**
[16:58:34 ERROR]: [org.bukkit.craftbukkit.v1_16_R3.CraftServer] failed to access class dev.jorel.commandapi.Config from class dev.jorel.commandapi.CommandAPIMain (dev.jorel.commandapi.Config is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @18948358; dev.jorel.commandapi.CommandAPIMain is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @30e2473f) initializing CommandAPI v5.11 (Is it up to date?)

**Comment by JorelAli** [comment]
Whoops, looks like the CommandAPI is getting confused between the shaded version and the plugin version. Could you post your pom.xml or build.gradle file as well?

**Comment by joeyPark8** [comment]
I included commandAPI jar from https://commandapi.jorel.dev/5.11/installation.html. Is there another jar that I have to include instead of commandAPI.jar?

**Comment by JorelAli** [comment]
If you are shading the CommandAPI (which it appears you are given that you're using `CommandAPI.onLoad`, then you need to use the commandapi-shade jar which can be found here: https://github.com/JorelAli/CommandAPI/tree/mvn-repo/dev/jorel/commandapi-shade/5.11

**Comment by joeyPark8** [comment]
I tried both, but I still have an error

[08:53:11 ERROR]: [org.bukkit.craftbukkit.v1_16_R3.CraftServer] failed to access class dev.jorel.commandapi.Config from class dev.jorel.commandapi.CommandAPIMain (dev.jorel.commandapi.Config is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @4a2f72d8; dev.jorel.commandapi.CommandAPIMain is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @f0fde8e) initializing CommandAPI v5.11 (Is it up to date?)
java.lang.IllegalAccessError: failed to access class dev.jorel.commandapi.Config from class dev.jorel.commandapi.CommandAPIMain (dev.jorel.commandapi.Config is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @4a2f72d8; dev.jorel.commandapi.CommandAPIMain is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @f0fde8e)
        at dev.jorel.commandapi.CommandAPIMain.onLoad(CommandAPIMain.java:16) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:394) ~[patched_1.16.5.jar:git-Paper-649]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:252) ~[patched_1.16.5.jar:git-Paper-649]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1065) ~[patched_1.16.5.jar:git-Paper-649]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-649]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by JorelAli** [comment]
You appear to have an invalid setup - your code should work as intended. Using a test environment, I was able to get everything working without issues.

In my server directory, I have the following:
```
.
├── paper-1.16.5-670.jar
├── plugins
│   ├── CommandAPI
│   │   └── config.yml
│   ├── CommandAPIIssue202.jar
│   └── CommandAPI.jar
├── server.properties
│
...
```
The `CommandAPI.jar` is the one from https://commandapi.jorel.dev/5.11/installation.html

In my project directory, I have the following:

```
.
├── bin
│   └── Main.class
├── plugin.yml
└── src
    └── Main.java
```

In `Main.java`, I have the following:
```java
import java.util.ArrayList;
import java.util.List;

import org.bukkit.ChatColor;
import org.bukkit.plugin.java.JavaPlugin;

import dev.jorel.commandapi.CommandAPICommand;
import dev.jorel.commandapi.CommandPermission;
import dev.jorel.commandapi.arguments.Argument;
import dev.jorel.commandapi.arguments.GreedyStringArgument;

public class Main extends JavaPlugin {

	@Override
	public void onLoad() {
        List<Argument> arguments = new ArrayList<>();

        arguments.add(new GreedyStringArgument("text"));

        new CommandAPICommand("boo")
                .withArguments(arguments)
                .withAliases("b")
                .withPermission(CommandPermission.OP)
                .executesPlayer((player, args) -> {
                    player.sendMessage(ChatColor.BOLD + "SUCCESS " + args[0]);
                    System.out.println("SUCCESS " + args[0]);
                })
                .register(); // You need to add .register() to register the command!
                
	}
	
}
```
And in `plugin.yml` I have the following:
```yml
name: CommandAPITest
main: Main
version: 1.0
depend: [CommandAPI]
```

-----

I don't quite know what you've managed to do, because it appears you've got confused with shading when you weren't shading originally or something? I have been able to confirm that the CommandAPI does indeed work as intended, so I'm not quite sure if I can help you - perhaps one of the above code blocks can help?

**Comment by joeyPark8** [comment]
Thank you for your help. The error is solved.
