### ISSUE TITLE
"java.lang.IllegalArgumentException: The permission is already defined!" when registering commands

### ISSUE THREAD

**Issue by willkroboth** [JorelAli/CommandAPI#214]
**CommandAPI version:** _6.0.0_

**Minecraft version:** _1.16.5_

**What I did:**
- Worked on developing a plugin with CommandAPI version 5.12, using a small paper server to test it
- Updated CommandAPI to 6.0 on my test server and in the project files for my plugin

**Actual result:**

`[08:43:38 ERROR]: Error occurred while enabling ConfigCommands v2.0.1 (Is it up to date?)
java.lang.IllegalArgumentException: The permission configcommands.warmwelcome is already defined!
	at org.bukkit.plugin.SimplePluginManager.addPermission(SimplePluginManager.java:741) ~[patched_1.16.5.jar:git-Paper-762]
	at org.bukkit.plugin.SimplePluginManager.addPermission(SimplePluginManager.java:733) ~[patched_1.16.5.jar:git-Paper-762]
	at dev.jorel.commandapi.CommandAPIHandler.generatePermissions(CommandAPIHandler.java:383) ~[?:?]
	at dev.jorel.commandapi.CommandAPIHandler.register(CommandAPIHandler.java:644) ~[?:?]
	at dev.jorel.commandapi.CommandAPICommand.register(CommandAPICommand.java:496) ~[?:?]
	at me.willkroboth.ConfigCommands.ConfigCommandExecutor.<init>(ConfigCommandExecutor.java:45) ~[?:?]
	at me.willkroboth.ConfigCommands.ConfigCommands.onEnable(ConfigCommands.java:102) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-762]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-762]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-762]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-762]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-762]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594) ~[patched_1.16.5.jar:git-Paper-762]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.16.5.jar:git-Paper-762]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069) ~[patched_1.16.5.jar:git-Paper-762]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-762]`

**What should have happened:**

- The command 'warmwelcome' with permission 'configcommand.warmwelcome' should have registered without an error like before

**How I tried to fix it**
- Changing the permission that the command is using
- Disabling the permissions plugin on the server, Luckperms

**Comment by JorelAli** [comment]
Hello, thanks for the bug report - In 6.0.0, I had tried to be smart about permission registration to improve performance and in fact, made it worse. The fix for this is trivial, so I will try and get a patch release out within 12 hours.

**Comment by JorelAli** [comment]
Fixed in 6.0.1's release.
