### ISSUE TITLE
NullPointerException when registering command with a multiliteral and another argument

### ISSUE THREAD

**Issue by willkroboth** [JorelAli/CommandAPI#217]
**CommandAPI version:** _6.0.1_

**Minecraft version:** _1.16.5_

**What I did:**

Registered a command with a multiliteral and another argument:
```
new CommandAPICommand("multiliteralTest")
                .withArguments(new MultiLiteralArgument("one", "two", "three"))
                .withArguments(new IntegerArgument("int", 1, 3))
                .executes((sender, args) -> {
                    String option = (String) args[0];
                    int integer = (int) args[1];
                    sender.sendMessage("You chose " + option + " and " + integer);
                })
                .register();
```

**Actual result:**

```
[10:05:03 ERROR]: Error occurred while enabling commandapitest v1.0.1 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "dev.jorel.commandapi.arguments.Argument.getNodeName()" because "arg" is null
	at dev.jorel.commandapi.CommandAPIHandler.register(CommandAPIHandler.java:596) ~[?:?]
	at dev.jorel.commandapi.CommandAPIHandler.expandMultiLiterals(CommandAPIHandler.java:483) ~[?:?]
	at dev.jorel.commandapi.CommandAPIHandler.register(CommandAPIHandler.java:589) ~[?:?]
	at dev.jorel.commandapi.CommandAPICommand.register(CommandAPICommand.java:496) ~[?:?]
	at me.willkroboth.commandapitest.commandapitest.onEnable(commandapitest.java:54) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-762]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-762]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-762]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-762]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-762]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594) ~[patched_1.16.5.jar:git-Paper-762]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.16.5.jar:git-Paper-762]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069) ~[patched_1.16.5.jar:git-Paper-762]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-762]
	at java.lang.Thread.run(Thread.java:831) [?:?]

```

**What should have happened:**

This command should have successfully registered.

**Comment by JorelAli** [comment]
Fixed in 6.0.2
