### ISSUE TITLE
Error running with PaperMC

### ISSUE THREAD

**Issue by toddharrison** [JorelAli/CommandAPI#224]
**CommandAPI version:** _6.0.5_

**Minecraft version:** _paper-1.17-17_

**What I did:**

- Starting up the server

**Actual result:**

```
[14:02:26 WARN]: [CommandAPI] Task #386 for CommandAPI v6.0.5 generated an exception
java.lang.NoSuchMethodError: 'net.minecraft.server.packs.resources.IResourceManager net.minecraft.server.DataPackResources.i()'
	at dev.jorel.commandapi.nms.NMS_1_17_R1.reloadDataPacks(NMS_1_17_R1.java:861) ~[?:?]
	at dev.jorel.commandapi.CommandAPI.lambda$onEnable$0(CommandAPI.java:177) ~[?:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.jar:git-Paper-"33d6b6f"]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.17.jar:git-Paper-"33d6b6f"]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1127) ~[patched_1.17.jar:git-Paper-"33d6b6f"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-"33d6b6f"]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

**What should have happened:**

- Not sure if you are planning on supporting PaperMC for Minecraft 1.17, but this error occurs on startup.

**Comment by toddharrison** [comment]
Paper is in beta, it's possible that this will be resolved as they continue to complete the conversion.

**Comment by JorelAli** [comment]
Currently a paper issue, nothing to do with the CommandAPI I'm afraid!
https://github.com/papermc/paperweight/issues/24

**Comment by JorelAli** [comment]
This should now be fixed in Paper build 40 due to a hotfix which fixes the underlying issue.
