### ISSUE TITLE
RuntimeException when enabling plugin

### ISSUE THREAD

**Issue by jho5245** [JorelAli/CommandAPI#237]
**CommandAPI version:** _6.2.0_ (NOT shaded version)

**Minecraft version:** _1.17.1_

Server version : Paper-139

**What I did:**
I just updated from 6.1.0 to 6.2.0 and removed shading and used plugin CommandAPI

**Actual result:**
An exception occurs when enabling my plugin
```
Stuff that happened when I did it (post error logs here for example)
```

java.lang.RuntimeException: You have the wrong copy of the CommandAPI! Make sure to use the one from https://github.com/JorelAli/CommandAPI/releases
[17:51:17 WARN]:        at dev.jorel.commandapi.CommandAPIVersionHandler.getNMS(CommandAPIVersionHandler.java:40)
[17:51:17 WARN]:        at dev.jorel.commandapi.CommandAPIHandler.<init>(CommandAPIHandler.java:140)
[17:51:17 WARN]:        at dev.jorel.commandapi.CommandAPIHandler.getInstance(CommandAPIHandler.java:127)
[17:51:17 WARN]:        at dev.jorel.commandapi.Brigadier.fromLiteralArgument(Brigadier.java:84)

**What should have happened:**

no exceptions if normal

**Comment by jho5245** [comment]
oops that was my fault, i didnt check the maven.yml correctly. Im so sorry for this.
