### ISSUE TITLE
Plugin Not Loaded when Converting Commands

### ISSUE THREAD

**Issue by PrestonHager** [JorelAli/CommandAPI#255]
**CommandAPI version:** _6.5.3_

**Minecraft version:** _PaperMC 1.18.1_

**What I did:**

- Install CommandAPI and Multiverse-Core
- Modify CommandAPI `config.yml` to
  ```
  plugins-to-convert:
    - Mutliverse-Core: ~
  ```

**Actual result:**

```
[16:25:08] [Server thread/WARN]: org.bukkit.plugin.InvalidPluginException: Could not find a plugin Mutliverse-Core! Has it been loaded properly?
[16:25:08] [Server thread/WARN]: at CommandAPI.jar//dev.jorel.commandapi.Config.<init>(Config.java:96)
[16:25:08] [Server thread/WARN]: at CommandAPI.jar//dev.jorel.commandapi.CommandAPIMain.onLoad(CommandAPIMain.java:34)[16:25:08] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_18_R1.CraftServer.loadPlugins(CraftServer.java:427)
[16:25:08] [Server thread/WARN]: at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:285)
[16:25:08] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1202)
[16:25:08] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[16:25:08] [Server thread/WARN]: at java.base/java.lang.Thread.run(Thread.java:833)
```

**What should have happened:**

The Multiverse-Core plugin should have been loaded before CommandAPI tried to access its commands. This can be done individually through the `plugin.yml` file under dependencies. However, is there a way to do it programmatically? Such that the plugin either doesn't load until all others do or waits asynchronously until the required plugin has been loaded?

As a server owner, I can modify the config file or drop in a custom version of the CommandAPI plugin. However, I would rather not go into the source code and modify one line each time I add a new plugin to the server.

**Comment by JorelAli** [comment]
If you're using the `config.yml` above:

```yml
plugins-to-convert:
  - Mutliverse-Core: ~
```

Note that you've written `Mutliverse` instead of `Multiverse`

**Comment by PrestonHager** [comment]
Usually, I catch those typos. Fixing the `config.yml` worked and it now converts the commands before the plugin is necessarily loaded. Thank you for your help! Sorry to clutter up the issues.
