### ISSUE TITLE
CommandAPI doesn't support particles with existing data parameters

### ISSUE THREAD

**Issue by JorelAli** [JorelAli/CommandAPI#273]
**CommandAPI version:** _7.0.0_

**Minecraft version:** _1.18.2_

**What I did:**

Run this code:

```java
new CommandAPICommand("dparticle")
	.withArguments(new ParticleArgument("particle"))
	.executesPlayer(((sender, args) -> {
	 System.out.println(Arrays.toString(args));
	    Particle particle = (Particle) args[0];
	    sender.getWorld().spawnParticle(particle, sender.getLocation(), 1);
	}))
	.register();
```

- Run `/dparticle dust 0 0 0 1` in-game

**Actual result:**

```
[14:45:46 INFO]: Skepter issued server command: /dparticle dust 0 0 0 1
[14:45:46 INFO]: [CommandAPI] [STDOUT] [REDSTONE]
[14:45:46 WARN]: Nag author(s): '[Skepter]' of 'CommandAPI' about their usage of System.out/err.print. Please use your plugin's logger instead (JavaPlugin#getLogger).
[14:45:46 INFO]: java.lang.IllegalArgumentException: Particle REDSTONE requires data, null provided
[14:45:46 INFO]:        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:220)
[14:45:46 INFO]:        at org.bukkit.craftbukkit.v1_18_R2.CraftParticle.toNMS(CraftParticle.java:172)
[14:45:46 INFO]:        at org.bukkit.craftbukkit.v1_18_R2.CraftWorld.spawnParticle(CraftWorld.java:2064)
[14:45:46 INFO]:        at org.bukkit.craftbukkit.v1_18_R2.CraftWorld.spawnParticle(CraftWorld.java:2054)
[14:45:46 INFO]:        at org.bukkit.craftbukkit.v1_18_R2.CraftWorld.spawnParticle(CraftWorld.java:2043)
[14:45:46 INFO]:        at org.bukkit.craftbukkit.v1_18_R2.CraftWorld.spawnParticle(CraftWorld.java:2023)
[14:45:46 INFO]:        at org.bukkit.craftbukkit.v1_18_R2.CraftWorld.spawnParticle(CraftWorld.java:2003)
[14:45:46 INFO]:        at org.bukkit.craftbukkit.v1_18_R2.CraftWorld.spawnParticle(CraftWorld.java:1993)
[14:45:46 INFO]:        at org.bukkit.craftbukkit.v1_18_R2.CraftWorld.spawnParticle(CraftWorld.java:1988)
[14:45:46 INFO]:        at CommandAPI-7.0.0_25_Apr_2022_(01-44-22pm).jar//dev.jorel.commandapi.CommandAPIMain.lambda$onEnable$0(CommandAPIMain.java:71)
[14:45:46 INFO]:        at CommandAPI-7.0.0_25_Apr_2022_(01-44-22pm).jar//dev.jorel.commandapi.executors.PlayerCommandExecutor.run(PlayerCommandExecutor.java:30)
[14:45:46 INFO]:        at CommandAPI-7.0.0_25_Apr_2022_(01-44-22pm).jar//dev.jorel.commandapi.executors.IExecutorNormal.executeWith(IExecutorNormal.java:43)
[14:45:46 INFO]:        at CommandAPI-7.0.0_25_Apr_2022_(01-44-22pm).jar//dev.jorel.commandapi.CustomCommandExecutor.execute(CustomCommandExecutor.java:116)
[14:45:46 INFO]:        at CommandAPI-7.0.0_25_Apr_2022_(01-44-22pm).jar//dev.jorel.commandapi.CustomCommandExecutor.execute(CustomCommandExecutor.java:94)
[14:45:46 INFO]:        at CommandAPI-7.0.0_25_Apr_2022_(01-44-22pm).jar//dev.jorel.commandapi.CustomCommandExecutor.execute(CustomCommandExecutor.java:80)
[14:45:46 INFO]:        at CommandAPI-7.0.0_25_Apr_2022_(01-44-22pm).jar//dev.jorel.commandapi.CommandAPIHandler.lambda$generateCommand$0(CommandAPIHandler.java:289)
[14:45:46 INFO]:        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263)
[14:45:46 INFO]:        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:177)
[14:45:46 INFO]:        at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:293)
[14:45:46 INFO]:        at org.bukkit.craftbukkit.v1_18_R2.command.VanillaCommandWrapper.execute(VanillaCommandWrapper.java:45)
[14:45:46 INFO]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[14:45:46 INFO]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:905)
[14:45:46 INFO]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2297)
[14:45:46 INFO]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2108)
[14:45:46 INFO]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2089)
[14:45:46 INFO]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[14:45:46 INFO]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[14:45:46 INFO]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
[14:45:46 INFO]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[14:45:46 INFO]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[14:45:46 INFO]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:23)
[14:45:46 INFO]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1401)
[14:45:46 INFO]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:189)
[14:45:46 INFO]:        at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:126)
[14:45:46 INFO]:        at net.minecraft.server.MinecraftServer.be(MinecraftServer.java:1378)
[14:45:46 INFO]:        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1371)
[14:45:46 INFO]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[14:45:46 INFO]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1349)
[14:45:46 INFO]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1231)
[14:45:46 INFO]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[14:45:46 INFO]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

**What should have happened:**

- The CommandAPI needs to support particles with existing parameters. This means that the CommandAPI shouldn't be returning a `org.bukkit.Particle`, but may have to provide some wrapper (or otherwise) to contain this information!

**Comment by JorelAli** [comment]
Implemented in 8.0.0.
