### ISSUE TITLE
CommandAPI.fail() not working for v8.0.0

### ISSUE THREAD

**Issue by iiiii7d** [JorelAli/CommandAPI#278]
**CommandAPI version:** _8.0.0_

**Minecraft version:** _1.18.2_

**What I did:**

```java
CommandAPICommand("cmd")
    .executes((sender, args) -> {
        throw CommandAPI.fail("This wouldn't show");
    })
    .register()
```

**Actual result:**

v8 shows nothing and produces an error instead (stuff in [] are redacted):
```java
[14:02:13 INFO]: java.lang.NullPointerException: Cannot invoke "com.mojang.brigadier.exceptions.CommandSyntaxException.fillInStackTrace()" because "this.exception" is null
[14:02:13 INFO]: 	at [plugin jar file]//dev.jorel.commandapi.exceptions.WrapperCommandSyntaxException.fillInStackTrace(WrapperCommandSyntaxException.java:65)
[14:02:13 INFO]: 	at java.base/java.lang.Throwable.<init>(Throwable.java:256)
[14:02:13 INFO]: 	at java.base/java.lang.Exception.<init>(Exception.java:55)
[14:02:13 INFO]: 	at [plugin jar file]//dev.jorel.commandapi.exceptions.WrapperCommandSyntaxException.<init>(WrapperCommandSyntaxException.java:47)
[14:02:13 INFO]: 	at [plugin jar file]//dev.jorel.commandapi.CommandAPI.fail(CommandAPI.java:222)
[14:02:13 INFO]: 	at [plugin jar file]//[package].onLoad$lambda-0([package].kt:44)
[14:02:13 INFO]: 	at [plugin jar file]//dev.jorel.commandapi.executors.IExecutorNormal.executeWith(IExecutorNormal.java:43)
[14:02:13 INFO]: 	at [plugin jar file]//dev.jorel.commandapi.CustomCommandExecutor.execute(CustomCommandExecutor.java:116)
[14:02:13 INFO]: 	at [plugin jar file]//dev.jorel.commandapi.CustomCommandExecutor.execute(CustomCommandExecutor.java:104)
[14:02:13 INFO]: 	at [plugin jar file]//dev.jorel.commandapi.CustomCommandExecutor.execute(CustomCommandExecutor.java:80)
[14:02:13 INFO]: 	at [plugin jar file]//dev.jorel.commandapi.CommandAPIHandler.lambda$generateCommand$0(CommandAPIHandler.java:289)
[14:02:13 INFO]: 	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263)
[14:02:13 INFO]: 	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:177)
[14:02:13 INFO]: 	at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:293)
[14:02:13 INFO]: 	at org.bukkit.craftbukkit.v1_18_R2.command.VanillaCommandWrapper.execute(VanillaCommandWrapper.java:45)
[14:02:13 INFO]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[14:02:13 INFO]: 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:905)
[14:02:13 INFO]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2306)
[14:02:13 INFO]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2117)
[14:02:13 INFO]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2098)
[14:02:13 INFO]: 	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[14:02:13 INFO]: 	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[14:02:13 INFO]: 	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
[14:02:13 INFO]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[14:02:13 INFO]: 	at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[14:02:13 INFO]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:23)
[14:02:13 INFO]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1399)
[14:02:13 INFO]: 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188)
[14:02:13 INFO]: 	at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:126)
[14:02:13 INFO]: 	at net.minecraft.server.MinecraftServer.be(MinecraftServer.java:1376)
[14:02:13 INFO]: 	at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1369)
[14:02:13 INFO]: 	at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[14:02:13 INFO]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1347)
[14:02:13 INFO]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1229)
[14:02:13 INFO]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[14:02:13 INFO]: 	at java.base/java.lang.Thread.run(Thread.java:833)
```

**What should have happened:**

v7 works fine, and shows `This wouldn't show` as an error

**Comment by TheGatesScratch** [comment]
Looking at the code I cannot see any way this.exception could be null. Very weird.

**Comment by JorelAli** [comment]
I'm aware of this issue. This will be fixed in the next release in a few days time and the fix has already been committed to the `dev/dev` branch.
