### ISSUE TITLE
CommandAPI can't handle very simple Skript command

### ISSUE THREAD

**Issue by JorelAli** [JorelAli/CommandAPI#288]
**CommandAPI version:** _8.2.0_

**Minecraft version:** _1.18.2_

**What I did:**

- Use Skript (2.6.1) with this script:

  ```yml
  command /broadcast [<text>]:
      trigger:
          broadcast " %colored arg-1%"
  ```

- Use CommandAPI plugin with this config:

  ```yml
  other-commands-to-convert:
    - /broadcast
  ```

**Actual result:** Console goes 💥:

```log
[19:50:15 INFO]: PLAYER issued server command: /execute as @a at @s run /broadcast @s
[19:50:15 INFO]: org.bukkit.command.CommandException: Unhandled exception executing '/broadcast @s' in org.bukkit.craftbukkit.v1_18_R2.command.VanillaCommandWrapper(/broadcast)[19:50:15 INFO]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:169)
[19:50:15 INFO]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906)
[19:50:15 INFO]:        at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:959)
[19:50:15 INFO]:        at CommandAPI-8.2.0.jar//dev.jorel.commandapi.Converter.lambda$convertCommand$1(Converter.java:141)
[19:50:15 INFO]:        at CommandAPI-8.2.0.jar//dev.jorel.commandapi.executors.NativeCommandExecutor.run(NativeCommandExecutor.java:29)
[19:50:15 INFO]:        at CommandAPI-8.2.0.jar//dev.jorel.commandapi.executors.IExecutorNormal.executeWith(IExecutorNormal.java:43)
[19:50:15 INFO]:        at CommandAPI-8.2.0.jar//dev.jorel.commandapi.CustomCommandExecutor.execute(CustomCommandExecutor.java:116)
[19:50:15 INFO]:        at CommandAPI-8.2.0.jar//dev.jorel.commandapi.CustomCommandExecutor.execute(CustomCommandExecutor.java:92)
[19:50:15 INFO]:        at CommandAPI-8.2.0.jar//dev.jorel.commandapi.CustomCommandExecutor.execute(CustomCommandExecutor.java:80)
[19:50:15 INFO]:        at CommandAPI-8.2.0.jar//dev.jorel.commandapi.CommandAPIHandler.lambda$generateCommand$0(CommandAPIHandler.java:284)
[19:50:15 INFO]:        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
[19:50:15 INFO]:        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:178)
[19:50:15 INFO]:        at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:293)
[19:50:15 INFO]:        at org.bukkit.craftbukkit.v1_18_R2.command.VanillaCommandWrapper.execute(VanillaCommandWrapper.java:45)
[19:50:15 INFO]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[19:50:15 INFO]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906)
[19:50:15 INFO]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2306)
[19:50:15 INFO]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2117)
[19:50:15 INFO]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2098)
[19:50:15 INFO]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[19:50:15 INFO]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[19:50:15 INFO]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
[19:50:15 INFO]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[19:50:15 INFO]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[19:50:15 INFO]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[19:50:15 INFO]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1399)
[19:50:15 INFO]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188)
[19:50:15 INFO]:        at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:126)
[19:50:15 INFO]:        at net.minecraft.server.MinecraftServer.be(MinecraftServer.java:1376)
[19:50:15 INFO]:        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1369)
[19:50:15 INFO]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[19:50:15 INFO]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1347)
[19:50:15 INFO]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1229)
[19:50:15 INFO]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[19:50:15 INFO]:        at java.base/java.lang.Thread.run(Thread.java:833)
[19:50:15 INFO]: Caused by: java.lang.IllegalArgumentException: Cannot make CraftPlayer{name=PLAYER} a vanilla command listener
[19:50:15 INFO]:        at org.bukkit.craftbukkit.v1_18_R2.command.VanillaCommandWrapper.getListener(VanillaCommandWrapper.java:93)
[19:50:15 INFO]:        at org.bukkit.craftbukkit.v1_18_R2.command.VanillaCommandWrapper.execute(VanillaCommandWrapper.java:44)
[19:50:15 INFO]:        at org.bukkit.command.SimpleCommandMap.dispatch(S
```

**What should have happened:** The command works

**Comment by JorelAli** [comment]
Turns out the root cause of the issue is the `/` in:
```yml
other-commands-to-convert:
  - /broadcast
```
