### ISSUE TITLE
NoSuchMethodError with SuggestionsBuilder.getRemainingLowerCase()

### ISSUE THREAD

**Issue by BeefDev** [JorelAli/CommandAPI#297]
**CommandAPI version:** _8.4.0_

**Minecraft version:** _1.16.5_

**What I did:** 

- Wrote a custom argument that has a StringArgument as a base. It uses the string to get a "profile" from the sender (basically in my plugin all players have profiles and you can get these by name (player.getProfile("name")).  
- The problem happens with ArgumentSuggestions.replaceSuggestions(ArgumentSuggestions.strings()). 

The only other plugin I have is ViaVersion

**Actual result:**

Server shuts down with this error
```txt
Encountered an unexpected exception
java.lang.NoSuchMethodError: 'java.lang.String com.mojang.brigadier.suggestion.SuggestionsBuilder.getRemainingLowerCase()'
	at io.github.beefdev.profiles.plugin.commandapi.arguments.ArgumentSuggestions.toSuggestions(ArgumentSuggestions.java:110) ~[?:?]
	at io.github.beefdev.profiles.plugin.commandapi.arguments.ArgumentSuggestions.lambda$strings$2(ArgumentSuggestions.java:59) ~[?:?]
	at io.github.beefdev.profiles.plugin.commandapi.CommandAPIHandler.lambda$toSuggestions$7(CommandAPIHandler.java:861) ~[?:?]
	at com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:71) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:596) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:579) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:720) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.PacketPlayInTabComplete.a(SourceFile:35) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.PacketPlayInTabComplete.a(SourceFile:9) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:28) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1061) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1054) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1038) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:970) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

**What should have happened:**

- The suggestion should have been shown in chat.

**Comment by JorelAli** [comment]
Fixed in 8.5.0.
