### ISSUE TITLE
Command conversion for 9.0.0 fails to cast arguments correctly

### ISSUE THREAD

**Issue by JorelAli** [JorelAli/CommandAPI#392]
Appears to have been introduced in 340902c467a6a5e1051d08895fbfe1f89f1eb2a8

```java
[13:44:56 INFO]: java.lang.ClassCastException: class [Ljava.lang.Object; cannot be cast to class [Ljava.lang.String; ([Ljava.lang.Object; and [Ljava.lang.String; are in module java.base of loader 'bootstrap')
[13:44:56 INFO]:        at CommandAPI-9.0.0-SNAPSHOT_02_Jan_2023_(01-25-53pm).jar//dev.jorel.commandapi.Converter.lambda$convertPluginCommand$2(Converter.java:202)
[13:44:56 INFO]:        at CommandAPI-9.0.0-SNAPSHOT_02_Jan_2023_(01-25-53pm).jar//dev.jorel.commandapi.executors.NativeCommandExecutor.run(NativeCommandExecutor.java:49)
[13:44:56 INFO]:        at CommandAPI-9.0.0-SNAPSHOT_02_Jan_2023_(01-25-53pm).jar//dev.jorel.commandapi.executors.NormalExecutor.executeWith(NormalExecutor.java:40)
[13:44:56 INFO]:        at CommandAPI-9.0.0-SNAPSHOT_02_Jan_2023_(01-25-53pm).jar//dev.jorel.commandapi.Converter.lambda$convertPluginCommand$3(Converter.java:211)
[13:44:56 INFO]:        at CommandAPI-9.0.0-SNAPSHOT_02_Jan_2023_(01-25-53pm).jar//dev.jorel.commandapi.executors.NativeCommandExecutor.run(NativeCommandExecutor.java:49)
[13:44:56 INFO]:        at CommandAPI-9.0.0-SNAPSHOT_02_Jan_2023_(01-25-53pm).jar//dev.jorel.commandapi.executors.NormalExecutor.executeWith(NormalExecutor.java:40)
[13:44:56 INFO]:        at CommandAPI-9.0.0-SNAPSHOT_02_Jan_2023_(01-25-53pm).jar//dev.jorel.commandapi.CommandAPIExecutor.execute(CommandAPIExecutor.java:117)
[13:44:56 INFO]:        at CommandAPI-9.0.0-SNAPSHOT_02_Jan_2023_(01-25-53pm).jar//dev.jorel.commandapi.CommandAPIExecutor.execute(CommandAPIExecutor.java:92)
[13:44:56 INFO]:        at CommandAPI-9.0.0-SNAPSHOT_02_Jan_2023_(01-25-53pm).jar//dev.jorel.commandapi.CommandAPIExecutor.execute(CommandAPIExecutor.java:79)
[13:44:56 INFO]:        at CommandAPI-9.0.0-SNAPSHOT_02_Jan_2023_(01-25-53pm).jar//dev.jorel.commandapi.CommandAPIHandler.lambda$generateCommand$0(CommandAPIHandler.java:245)
[13:44:56 INFO]:        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
[13:44:56 INFO]:        at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:313)
[13:44:56 INFO]:        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:297)
[13:44:56 INFO]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2286)
[13:44:56 INFO]:        at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$20(PlayerConnection.java:2248)
[13:44:56 INFO]:        at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[13:44:56 INFO]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[13:44:56 INFO]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[13:44:56 INFO]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[13:44:56 INFO]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[13:44:56 INFO]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1341)
[13:44:56 INFO]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[13:44:56 INFO]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[13:44:56 INFO]:        at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1318)
[13:44:56 INFO]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1311)
[13:44:56 INFO]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[13:44:56 INFO]:        at net.minecraft.server.MinecraftServer.i_(MinecraftServer.java:1289)
[13:44:56 INFO]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1177)
[13:44:56 INFO]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[13:44:56 INFO]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

https://github.com/JorelAli/CommandAPI/blob/49741e3bfc5e4ecd0e7a18102f081e00e14e9471/commandapi-platforms/commandapi-bukkit/commandapi-bukkit-core/src/main/java/dev/jorel/commandapi/Converter.java#L202

-----

What I did:

- Convert a plugin command using the CommandAPI's plugin converter. For this specific test, I used [SneakHeads](https://github.com/CentralSeaServer/SneakHeads/releases/tag/1.4):

  ```yml
  plugins-to-convert:
    - SneakHeads:
      - sneakheads
  ```

- Run `/minecraft:sneakheads` in-game

Other info:

```
[13:52:37 INFO]: This server is running Paper version git-Paper-353 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 8e83c3c)
You are 14 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-173 (MC: 1.19.2)
```

**Comment by JorelAli** [comment]
Implemented in 9.0.0.
