### ISSUE TITLE
Command exceptions are stolen by the CommandAPI and don't bubble up to the console

### ISSUE THREAD

**Issue by JorelAli** [JorelAli/CommandAPI#446]
### CommandAPI version

9.0.1

### Minecraft version

1.19.3

### Are you shading the CommandAPI?

No

### What I did

- Register this command:

  ```java
  new CommandAPICommand("somecommand")
  	.executes((sender, args) -> {
  		if (true) {
  			throw new StackOverflowError("test");
  		}
  		return;
  	})
  	.register();
  ```
- Run the command as a player in-game

### What actually happened

Nothing. No errors appear in the console, no errors are sent to the user

### What should have happened

A stack trace makes its way to the console, something like this:
```
[10:08:54 WARN]: Unexpected exception while parsing console command "somecommand"
org.bukkit.command.CommandException: Unhandled exception executing 'somecommand' in org.bukkit.craftbukkit.v1_19_R3.command.VanillaCommandWrapper(somecommand)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:165) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchCommand(CraftServer.java:906) ~[paper-1.19.4.jar:git-Paper-527]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchServerCommand(CraftServer.java:869) ~[paper-1.19.4.jar:git-Paper-527]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:501) ~[paper-1.19.4.jar:git-Paper-527]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:448) ~[paper-1.19.4.jar:git-Paper-527]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.4.jar:git-Paper-527]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.19.4.jar:git-Paper-527]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-527]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.StackOverflowError: test
        at dev.jorel.commandapi.CommandAPIMain.lambda$onEnable$1(CommandAPIMain.java:229) ~[CommandAPI-9.0.2_12_May_2023_(09-08-08am).jar:?]
        at dev.jorel.commandapi.executors.CommandExecutor.run(CommandExecutor.java:49) ~[CommandAPI-9.0.2_12_May_2023_(09-08-08am).jar:?]
        at dev.jorel.commandapi.executors.NormalExecutor.executeWith(NormalExecutor.java:40) ~[CommandAPI-9.0.2_12_May_2023_(09-08-08am).jar:?]
        at dev.jorel.commandapi.CommandAPIExecutor.execute(CommandAPIExecutor.java:117) ~[CommandAPI-9.0.2_12_May_2023_(09-08-08am).jar:?]
        at dev.jorel.commandapi.CommandAPIExecutor.execute(CommandAPIExecutor.java:104) ~[CommandAPI-9.0.2_12_May_2023_(09-08-08am).jar:?]
        at dev.jorel.commandapi.CommandAPIExecutor.execute(CommandAPIExecutor.java:79) ~[CommandAPI-9.0.2_12_May_2023_(09-08-08am).jar:?]
        at dev.jorel.commandapi.CommandAPIHandler.lambda$generateCommand$0(CommandAPIHandler.java:252) ~[CommandAPI-9.0.2_12_May_2023_(09-08-08am).jar:?]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[paper-1.19.4.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:322) ~[?:?]
        at net.minecraft.commands.Commands.performPrefixedCommand(Commands.java:301) ~[?:?]
        at org.bukkit.craftbukkit.v1_19_R3.command.VanillaCommandWrapper.execute(VanillaCommandWrapper.java:45) ~[paper-1.19.4.jar:git-Paper-527]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        ... 8 more
```

### Other

Raised from [this message](https://discord.com/channels/745416925924032523/745757702608912556/1106013876862074970) from the CommandAPI Discord.

**Comment by JorelAli** [comment]
Two main issues seem to be the cause of this.
When running a command from the console, commands are fired via `CraftServer#dispatchServerCommand`:
```ini
org.bukkit.command.CommandException: Unhandled exception executing 'somecommand' in org.bukkit.craftbukkit.v1_19_R3.command.VanillaCommandWrapper(somecommand)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:165) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchCommand(CraftServer.java:906) ~[paper-1.19.4.jar:git-Paper-527]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchServerCommand(CraftServer.java:869) ~[paper-1.19.4.jar:git-Paper-527]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:501) ~[paper-1.19.4.jar:git-Paper-527]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:448) ~[paper-1.19.4.jar:git-Paper-527]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.4.jar:git-Paper-527]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.19.4.jar:git-Paper-527]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-527]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
This then bubbles up to `SimpleCommandMap#dispatch` which can catch `Throwable` objects and prints them in the console accordingly. This is why errors are "properly" reported when run via the console. Notably, **commands are not executed via Brigadier** - they are run directly from Bukkit's CommandMap which is synchronized with the Brigadier command dispatcher.

When running a command as a player, we run directly via brigadier, via `CommandDispatcher#execute`:

```ini
[10:56:33 WARN]:        at CommandAPI-9.0.2_12_May_2023_(09-45-42am).jar//dev.jorel.commandapi.executors.CommandExecutor.run(CommandExecutor.java:49)
[10:56:33 WARN]:        at CommandAPI-9.0.2_12_May_2023_(09-45-42am).jar//dev.jorel.commandapi.executors.NormalExecutor.executeWith(NormalExecutor.java:40)
[10:56:33 WARN]:        at CommandAPI-9.0.2_12_May_2023_(09-45-42am).jar//dev.jorel.commandapi.CommandAPIExecutor.execute(CommandAPIExecutor.java:117)
[10:56:33 WARN]:        at CommandAPI-9.0.2_12_May_2023_(09-45-42am).jar//dev.jorel.commandapi.CommandAPIExecutor.execute(CommandAPIExecutor.java:104)
[10:56:33 WARN]:        at CommandAPI-9.0.2_12_May_2023_(09-45-42am).jar//dev.jorel.commandapi.CommandAPIExecutor.execute(CommandAPIExecutor.java:79)
[10:56:33 WARN]:        at CommandAPI-9.0.2_12_May_2023_(09-45-42am).jar//dev.jorel.commandapi.CommandAPIHandler.lambda$generateCommand$0(CommandAPIHandler.java:252)
[10:56:33 WARN]:        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
[10:56:33 WARN]:        at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:322)
[10:56:33 WARN]:        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:306)
[10:56:33 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2291)
[10:56:33 WARN]:        at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$20(PlayerConnection.java:2251)
```
The `net.minecraft.server.CommandDispatcher#performCommand` can catch `
net.minecraft.commands.CommandException`, `CommandSyntaxException` and `Exception` objects, but never `Throwable` objects. When it catches an `Exception`, it doesn't print this to the console, instead it forwards it to the client:

<img width="587" alt="image" src="https://github.com/JorelAli/CommandAPI/assets/4613171/c8c382aa-b0a8-4383-bba0-7089c78318f3">

We can rectify this by putting a custom exception handler in the same way Bukkit does by wrapping around Bukkit's `CommandException`, or by directly throwing to `System.err` (or the equivalent logger print stream), and ensure this doesn't fire when running as a console?
