### ISSUE TITLE
The CommandAPI produces a NullPointerException when running a command as a remote command sender

### ISSUE THREAD

**Issue by JorelAli** [JorelAli/CommandAPI#447]
### CommandAPI version

9.0.1

### Minecraft version

1.19.3

### Are you shading the CommandAPI?

No

### What I did

- Download [ServerTap 0.5.2](https://github.com/phybros/servertap/releases/tag/v0.5.2)
- Download [SimpleBukkitPlugin 1.0.0](https://github.com/JorelAli/SimpleBukkitPlugin/releases/tag/1.0.0)
- Add `SimpleBukkitPlugin` to the CommandAPI's config.yml file:

  ```yml
  # Plugins to convert (default: [])
  # Controls the list of plugins to process for command conversion.
  plugins-to-convert:
    - SimpleBukkitPlugin: ~
  ```
- Run a paper server
- Go to http://localhost:4567/swagger#/Server/post_v1_server_exec
- Click "Try it out" in the top right corner of the `/v1/server/exec` request
- Fill out the form with:
  - `key`: `change_me`
  - `command`: `execute run mycommand`
  - `time`: `0`
- Press `Execute` in the web UI.

### What actually happened

CommandAPI doesn't run the command and errors:
```ini
[15:02:53 ERROR]: [CommandAPI] Unhandled exception executing '/execute run mycommand'
java.lang.NullPointerException: Cannot invoke "Object.getClass()" because the return value of "dev.jorel.commandapi.wrappers.NativeProxyCommandSender.getCallee()" is null
        at dev.jorel.commandapi.Converter.mergeProxySender(Converter.java:239) ~[CommandAPI-9.0.2_12_May_2023_(01-59-23pm).jar:?]
        at dev.jorel.commandapi.Converter.lambda$convertPluginCommand$2(Converter.java:205) ~[CommandAPI-9.0.2_12_May_2023_(01-59-23pm).jar:?]
        at dev.jorel.commandapi.executors.NativeCommandExecutor.run(NativeCommandExecutor.java:49) ~[CommandAPI-9.0.2_12_May_2023_(01-59-23pm).jar:?]
        at dev.jorel.commandapi.executors.NormalExecutor.executeWith(NormalExecutor.java:40) ~[CommandAPI-9.0.2_12_May_2023_(01-59-23pm).jar:?]
        at dev.jorel.commandapi.CommandAPIExecutor.execute(CommandAPIExecutor.java:134) ~[CommandAPI-9.0.2_12_May_2023_(01-59-23pm).jar:?]
        at dev.jorel.commandapi.CommandAPIExecutor.execute(CommandAPIExecutor.java:109) ~[CommandAPI-9.0.2_12_May_2023_(01-59-23pm).jar:?]
        at dev.jorel.commandapi.CommandAPIExecutor.execute(CommandAPIExecutor.java:92) ~[CommandAPI-9.0.2_12_May_2023_(01-59-23pm).jar:?]
        at dev.jorel.commandapi.CommandAPIHandler.lambda$generateCommand$0(CommandAPIHandler.java:252) ~[CommandAPI-9.0.2_12_May_2023_(01-59-23pm).jar:?]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[paper-1.19.4.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:322) ~[?:?]
        at net.minecraft.commands.Commands.performPrefixedCommand(Commands.java:301) ~[?:?]
        at org.bukkit.craftbukkit.v1_19_R3.command.VanillaCommandWrapper.execute(VanillaCommandWrapper.java:45) ~[paper-1.19.4.jar:git-Paper-527]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchCommand(CraftServer.java:906) ~[paper-1.19.4.jar:git-Paper-527]
        at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:980) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.servertap.ServerExecCommandSender.lambda$executeCommand$0(ServerExecCommandSender.java:32) ~[ServerTap-0.5.2.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftFuture.run(CraftFuture.java:88) ~[paper-1.19.4.jar:git-Paper-527]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.4.jar:git-Paper-527]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1483) ~[paper-1.19.4.jar:git-Paper-527]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.4.jar:git-Paper-527]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.4.jar:git-Paper-527]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.19.4.jar:git-Paper-527]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-527]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### What should have happened

The command runs and `/mycommand was called :)` appears in the console

### Other

Raised from [this message](https://discord.com/channels/745416925924032523/745757702608912556/1106541439539757077) by PanetiX from the CommandAPI Discord.

**Comment by JorelAli** [comment]
Oh yeah, I forgot this was fixed! Fixed in release 9.0.2.
