### ISSUE TITLE
9.2.0 doesn't handle datapacks correctly

### ISSUE THREAD

**Issue by xHyroM** [JorelAli/CommandAPI#504]
### CommandAPI version

9.2.0

### Minecraft version

1.20.1

### Are you shading the CommandAPI?

Yes

### What I did

I just ran server with some plugins and datapacks

### What actually happened

Thrown error with `Failed to load datapacks, can't proceed with normal server load procedure. Try fixing your datapacks?`

### What should have happened

Everyhing should works as expected, registering recipes and all functions

### Server logs and CommandAPI config

```
[03:00:44] [Server thread/ERROR]: Failed to load function incendium:item/necrotic_shield/on_block
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Whilst parsing command on line 7: Incorrect argument for command at position 60: ...@s run tp <--[HERE]
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Whilst parsing command on line 7: Incorrect argument for command at position 60: ...@s run tp <--[HERE]
	at net.minecraft.commands.CommandFunction.fromLines(CommandFunction.java:68) ~[?:?]
	at net.minecraft.server.ServerFunctionLibrary.lambda$reload$2(ServerFunctionLibrary.java:80) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	... 3 more
[03:00:44] [Server thread/ERROR]: [CommandAPI] Failed to load datapacks, can't proceed with normal server load procedure. Try fixing your datapacks?
java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.RecipeChoice.clone()" because "this.template" is null
	at org.bukkit.inventory.SmithingTransformRecipe.getTemplate(SmithingTransformRecipe.java:50)
	at org.bukkit.craftbukkit.v1_20_R1.inventory.CraftSmithingTransformRecipe.addToCraftingManager(CraftSmithingTransformRecipe.java:32)
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.addRecipe(CraftServer.java:1544)
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.addRecipe(CraftServer.java:1510)
	at org.bukkit.Bukkit.addRecipe(Bukkit.java:1075)
	at lighteco-bukkit-0.1.0.jar//dev.xhyrom.lighteco.libraries.commandapi.CommandAPIBukkit.registerBukkitRecipesSafely(CommandAPIBukkit.java:688)
	at lighteco-bukkit-0.1.0.jar//dev.xhyrom.lighteco.libraries.commandapi.nms.NMS_1_20_R1.reloadDataPacks(NMS_1_20_R1.java:737)
	at lighteco-bukkit-0.1.0.jar//dev.xhyrom.lighteco.libraries.commandapi.CommandAPIBukkit.lambda$onEnable$0(CommandAPIBukkit.java:183)
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1127)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Other

We have two custom plugins that uses CommandAPI:
- KetchupManagement (this modifies commands like /tp), uses 9.0.3
- LightEco (just creates commands for economy purposes), uses 9.2.0

I tried disabling KetchupManagement and it still had problems registering recipes but not parsing the commands and then I tried both plugins but changed LightEco to use 9.0.3 and then it worked it perfectly

So there must be issue with smithing tables but also how the commands are registered (i know CommandAPI registers everyhing into `minecraft:` namespace, but why it has problems with parsing only on `9.2.0` and not `9.0.3` ?)

**Comment by xHyroM** [comment]
thanks!
