### ISSUE TITLE
Error when executing command many times

### ISSUE THREAD

**Issue by ImNotStable** [JorelAli/CommandAPI#519]
### CommandAPI version

9.3.0

### Minecraft version

1.18.2

### Are you shading the CommandAPI?

Yes

### What I did

This is the message I received from someone using my plugin

when i do /eco add 1000 in game i see "An unexpected error occured trying to execute that command" while the command still runs and i do still receive the money but in console it floods with this. for a server that is going to have this command run many times everyday due to crates being opened and rewards involving money this can make it hard to then go back to check logs when things such as roll backs happen where users loose huge amounts of their money.

### What actually happened

The console was spammed with errors

### What should have happened

I expected no error, the command runs as stated in the message above.

### Server logs and CommandAPI config

```
[21:28:57 INFO]: LmaoLoq issued server command: /eco LmaoLoq add 1000
d.java:70) ~[QualityEconomy-1.4.4.jar:?]
at com.imnotstable.qualityeconomy.commandapi.executors.CommandExecutor.run(CommandExecutor.java:49) ~[QualityEconomy-1.4.4.jar:?]
at com.imnotstable.qualityeconomy.commandapi.executors.NormalExecutor.executeWith(NormalExecutor.java:44) ~[QualityEconomy-1.4.4.jar:?]
at com.imnotstable.qualityeconomy.commandapi.CommandAPIExecutor.execute(CommandAPIExecutor.java:137) ~[QualityEconomy-1.4.4.jar:?]
at com.imnotstable.qualityeconomy.commandapi.CommandAPIExecutor.execute(CommandAPIExecutor.java:124) ~[QualityEconomy-1.4.4.jar:?]
at com.imnotstable.qualityeconomy.commandapi.CommandAPIExecutor.execute(CommandAPIExecutor.java:91) ~[QualityEconomy-1.4.4.jar:?]
at com.imnotstable.qualityeconomy.commandapi.CommandAPIHandler.lambda$generateCommand$0(CommandAPIHandler.java:258) ~[QualityEconomy-1.4.4.jar:?]
at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[paper-1.18.2.jar:?]
at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:178) ~[paper-1.18.2.jar:?]
at net.minecraft.commands.Commands.performCommand(Commands.java:293) ~[?:?]
at org.bukkit.craftbukkit.v1_18_R2.command.VanillaCommandWrapper.execute(VanillaCommandWrapper.java:45) ~[paper-1.18.2.jar:git-Paper-388]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1400) ~[paper-1.18.2.jar:git-Paper-388]
at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[paper-1.18.2.jar:git-Paper-388]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1377) ~[paper-1.18.2.jar:git-Paper-388]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1370) ~[paper-1.18.2.jar:git-Paper-388]
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1348) ~[paper-1.18.2.jar:git-Paper-388]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230) ~[paper-1.18.2.jar:git-Paper-388]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-388]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Other

I'm unsure how to replicate this issue.

**Comment by DerEchtePilz** [comment]
> when i do /eco add 1000 in game i see "An unexpected error occured trying to execute that command"

That sounds like something your code causes. In your logs I can see the class being cut off, do you mind sharing or double-checking the code that whatever class this is in line 70?

**Comment by ImNotStable** [comment]
Here you go
https://github.com/ImNotStable/QualityEconomy/blob/master/src/main/java/com/imnotstable/qualityeconomy/commands/EconomyCommand.java

**Comment by ImNotStable** [comment]
Hello @DerEchtePilz?

**Comment by DerEchtePilz** [comment]
Yeah, sorry for letting you wait.
I really believe this isn't a CommandAPI issue. There is clearly something cut off in your stacktrace which indicates your code is doing something which would cause an error during command execution (let it be something null that causes a NPE, or anything similar; I can tell it's your code since `CommandExecutor#run` is the last call the CommandAPI does, this calls the lambda, this means your command implementation).
I also saw you committed something to your code after sending the class which apparently catches a few edge cases (like formatting a number correctly).
So, I am going to close this for now but, by all means, if you are experiencing issues again, please reply here or open another issue.
